### ISSUE TITLE
Elasticsearch data format

### ISSUE THREAD

**Issue by mikehhhhhhh** [cyrilcherian/million-points-on-map#1]
Could you clarify the format in which you're putting data into elasticsearch for someone who is not quite as familiar with elasticsearch? 

Index was created with the supplied example

I've tried my data in this format (these being results from an empty search)

```
{
      "_index" : "points",
      "_type" : "point",
      "_id" : "AVEaYXOzCKM7Hs_jae0G",
      "_score" : 1.0,
      "_source":{"point":{"lat":13.964871,"lon":100.37347}}
 }
```

as well as

```
{
      "_index" : "points",
      "_type" : "point",
      "_id" : "AVEaYXOzCKM7Hs_jae0G",
      "_score" : 1.0,
      "_source":{"location":{"lat":13.964871,"lon":100.37347}}
 }
```

and 

```
{
      "_index" : "points",
      "_type" : "point",
      "_id" : "AVEaaPfmCKM7Hs_jae0T",
      "_score" : 1.0,
      "_source":{"point":{"location":{"lat":50.706843,"lon":-1.285245}}}
 }
```

and

```
{
      "_index" : "points",
      "_type" : "point",
      "_id" : "AVEaa4FrCKM7Hs_jae0e",
      "_score" : 1.0,
      "_source":{"point":[51.531011,-0.012336]}
}
```

But when running a query, I get the following;
    QueryParsingException[[points] failed to find geo_point field [point]]

**Comment by cyrilcherian** [comment]
I think you forgot to give the mapping before inserting the data as a result of which your mapping point is not geo_point field.
You can check your mapping by doing 

`curl -XGET 'http://YOUR_ELATIC:9200/points/_mapping`

How to get mapping details [read here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html)

My mapping is like this

```
{
  "points": {
    "mappings": {
      "point": {
        "properties": {
          "point": {
            "type": "geo_point"
          },
          "sentiment": {
            "type": "float"
          }
        }
      }
    }
  }
}
```

If they don't match delete the type as [shown here](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/indices-delete-index.html)
`curl -XDELETE 'http://YOUR_ELASTIC:9200/points/'`

Now you have to make an index and type like this [read here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#mappings)
So if you want an index **points** and type **point** you can create it like this

```
curl -XPOST YOUR_ELASTIC:9200/points -d '{
    "mappings": {
      "point": {
        "properties": {
          "point": {
            "type": "geo_point"
          },
          "sentiment": {
            "type": "float"
          }
        }
      }
    }

}'
```

Hope this helps!
